wmde/Diff

src/DiffOp/Diff/Diff.php
tests/phpunit/DiffOp/Diff/DiffAsOpTest.php
tests/phpunit/DiffOp/Diff/DiffTest.php
tests/phpunit/DiffOp/DiffOpAddTest.php
tests/phpunit/DiffOp/DiffOpChangeTest.php
tests/phpunit/DiffOp/DiffOpRemoveTest.php
tests/phpunit/DiffOp/DiffOpTest.php
tests/phpunit/DiffTestCase.php
tests/phpunit/Patcher/MapPatcherTest.php

I tried to make some of the pretty generic "array" type hints more specific.
Data providers always `@return array[]`, this is not worth documentation.

More specific array type hints/docs

---

composer.json

Remove "vendor/bin/" as suggested by @Krinkle in https://github.com/wmde/Diff/commit/acd15a05c6317c0a5a1ea446eca01123fce4bca1#commitcomment-9861167.
I'm also moving the `ci` command to the top.

Don't access vendor/bin in composer ci

---

src/DiffOp/AtomicDiffOp.php
src/DiffOp/Diff/Diff.php

Reasoning: `is_integer` is an alias for `is_int` in PHP.

Favor shortcut "int" in PHPDoc tags

---

README.md
src/Comparer/ValueComparer.php
src/DiffOp/AtomicDiffOp.php
src/DiffOp/Diff/Diff.php
src/DiffOp/DiffOp.php
src/Differ/MapDiffer.php
src/Patcher/ThrowingPatcher.php
tests/phpunit/DiffTestCase.php

Reasoning: `boolean` is an alias. `is_boolean` doesn't even exist in PHP.

Favor shortcut "bool" in PHPDoc tags

---

src/DiffOp/Diff/ListDiff.php
src/DiffOp/Diff/MapDiff.php
src/Differ/ListDiffer.php
tests/phpunit/DiffOp/Diff/ListDiffTest.php
tests/phpunit/Differ/ListDifferTest.php
tests/phpunit/Differ/MapDifferTest.php

This patch also replaces deprecated constants in 3 places in tests. Please double check that I'm not accidentally changing tests that do have the purpose of covering these deprecated constants.

Make @deprecated tags more descriptive

---

composer.json

I played around with PHPMD and am a bit disappointed. It's not possible to set a number like "this rule is allowed to be broken x times in the legacy code base, but report any new exception".
* Added ~~`composer md`~~ `composer phpcs` and `composer phpmd` commands.
* ~~`composer cs` does not execute PHPMD any more, but `composer ci` still does~~.
* ~~Re-enabled all rules with limits that are exactly as high as the current code is~~ (see #36).
* ~~Re-wrote one method because of the unused variables rule~~ (reverted).

Allow running phpmd separately

---

src/ArrayComparer/ArrayComparer.php
src/ArrayComparer/NativeArrayComparer.php
src/ArrayComparer/OrderedArrayComparer.php
src/ArrayComparer/StrategicArrayComparer.php
src/ArrayComparer/StrictArrayComparer.php
src/Comparer/CallbackComparer.php
src/Comparer/ValueComparer.php
src/DiffOp/AtomicDiffOp.php
src/DiffOp/Diff/Diff.php
src/DiffOp/Diff/ListDiff.php
src/DiffOp/Diff/MapDiff.php
src/DiffOp/DiffOp.php
src/DiffOp/DiffOpAdd.php
src/DiffOp/DiffOpChange.php
src/DiffOp/DiffOpRemove.php
src/DiffOpFactory.php
src/Differ/CallbackListDiffer.php
src/Differ/Differ.php
src/Differ/ListDiffer.php
src/Differ/MapDiffer.php
src/Differ/OrderedListDiffer.php
src/Patcher/ListPatcher.php
src/Patcher/MapPatcher.php
src/Patcher/Patcher.php
src/Patcher/PreviewablePatcher.php
src/Patcher/ThrowingPatcher.php

These tags on the method level are all identical to the same tag on the class level, therefore being redundant and not adding information that's not already there.

Remove redundant since tags

---

src/DiffOp/DiffOp.php
src/Patcher/PatcherException.php
tests/bootstrap.php
tests/phpunit/DiffOp/Diff/MapDiffTest.php

Plus some minor code style issues, mostly for consistency across the Wikibase code base:
* Avoid assertTrue with ===, there is assertSame for that.
* Unset global variable in test bootstrap.
* Add a missing doc block.

Avoid full qualified class names

---

phpcs.xml

In this case this is only for style, to have a uniform best practice across all our PHPCS rule sets.
When you exclude a whole sniff (e.g. "Vendor.Namespace.Sniff"), the sniff is not run and the test runs faster. This is not possible here, because this sniff can report two things, and only one should be disabled.

Exclude PHPCS messages instead of setting severity to 0

---

composer.json

This is to avoid getting a crapton of warnings when using recent PHPUnit
versions. Fun fact: we cannot avoid those warnings without becomming
unsable to run the build on PHPUnit older than 5.6 due to recent PHPUnit
requiring 5.6 or later, and it deprecating things for which the alternative
was introduced in those same versions. #MAW

Use composer installed PHPUnit in build

---

src/Patcher/MapPatcher.php

The elements in a Diff object are guaranteed to be DiffOp objects.

Add missing DiffOp type hint to MapPatcher

---

README.md

MapDiffer()->diff() method was undefined, changed to doDiff()

rename MapDiffer Method

---

composer.json

Effective lowerbound increased from 0.6.0 to 0.6.1

Upperbound ockcyp/covers-validator version

---

src/DiffOp/Diff/Diff.php

Instead of always iterating the entire tree, stop immediately when at least one atomic diff operation was found.
I'm also removing the methods description, which is actually not true.

Optimize Diff::isEmpty for performance

---

src/Patcher/ListPatcher.php
tests/phpunit/Patcher/ListPatcherTest.php

Background: discovered in Wikibase when trying to apply a patch removing an ItemId object from the list of ItemId objects. This failed if the "same" ID was in the list, but it was not technically the same object in memory.
While discussing the issue with @wiese and @jakobw, we've mentioned that further extension would be to allow to provide a function/object that would allow custom object comparison if something more sophisticated than PHP's native object non-strict comparison (i.e. all attribute and their values comparison) is needed. Not implemented here as there does not seem to be a use for such extension yet.

ListPatcher: use non-strict comparison when removing objects

---

Diff.php
RELEASE-NOTES.md
composer.json
src/Patcher/ListPatcher.php
tests/phpunit/Patcher/ListPatcherTest.php

This is backporting https://github.com/wmde/Diff/pull/92 onto PHP 5-compatible branch and makes a new release for the use in Wikibase.

ListPatcher object comparison fix - backport to 2.x branch and release 2.3.0

---

.travis.yml
Diff.php
README.md
src/DiffOp/Diff/Diff.php
src/DiffOp/DiffOpAdd.php
src/DiffOp/DiffOpChange.php
src/DiffOp/DiffOpRemove.php
tests/unit/DiffOp/Diff/DiffTest.php
tests/unit/DiffOp/DiffOpTest.php
tests/unit/Patcher/MapPatcherTest.php

Contains #129, one additional backwards compatibility fix and silences some deprecation notices from us mocking the `DiffOp` interface.
Tested with `PHP 8.1.10`.

Add PHP 8.1 compatibility

---

src/DiffOp/Diff/Diff.php
src/DiffOp/DiffOpAdd.php
src/DiffOp/DiffOpChange.php
src/DiffOp/DiffOpRemove.php

PHP 7 seems to have the method declared without the type hint and return type, causing warnings.

Make our __unserialize declarations match PHP 7's

---

.github/workflows/push.yaml

Initial workflow definition. Still to be added (to be in par with the existing travis CI build) are code coverage generation and publishing the results for scrutinizer, and sending notifications (email instead of IRC?) on, at least, failed runs

Added github actions workflow to lint and test when pushing code

---

.github/workflows/scrutinize.yaml

Further work to move over from Travis CI.
Includes the commit from https://github.com/wmde/Diff/pull/138
the only file really involved in this PR is `.github/workflows/scrutinize.yaml`

Add github actions CI workflow to generate and upload the test coverage to Scrutinizer

---

.github/workflows/ci_failure_email.md.tmpl
.github/workflows/push.yaml

Further work to move over from Travis CI.
Includes the commit from https://github.com/wmde/Diff/pull/138
Relevant commit for emails on failure is dc3b2b9605e018ffea5ad16c007ffe3035b8072e and following ones

GitHub actions email on failure

---

README.md
RELEASE-NOTES.md

* Drop support for PHP 7.2, 7.3
* Upgrade codesniffer rules to current `mediawiki/mediawiki-codesniffer` version (45.0.0)
* Make nullable type parameter declarations explicit for compatibility with PHP 8.4
Bug: T379481

Bump version to 3.4.0
